<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.appium</groupId>
    <artifactId>AppiumDemo</artifactId>
    <version>1.0</version>

    <dependencies>
        <!-- Appium Java Client -->
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>9.2.0</version>
        </dependency>

        <!-- TestNG -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.9.0</version>
        </dependency>
    </dependencies>
</project>