package com.example.stepdefinitions;

import io.cucumber.java.en.Given;
import io.cucumber.java.en.When;
import io.cucumber.java.en.Then;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.By;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import java.time.Duration;

/**
* Cucumber Step Definitions
* Generated by Selenium-Cucumber Extension
*
* This class contains step definitions for Cucumber scenarios.
* Each method represents a step that can be used in feature files.
*/
public class StepDefinitions {

    //private WebDriver driver;
    //private WebDriverWait wait;

    public StepDefinitions() {
        // Initialize WebDriver and WebDriverWait if needed
        // this.driver = DriverManager.getDriver();
        // this.wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    }

    /**
    * Step: Given I access the WebDriver University Contact Us Page
    */
    @Given("I access the WebDriver University Contact Us Page")
    public void i_access_the_webdriver_university_contact_us_page() {
        System.out.println("Test01");
    }

    /**
    * Step: When I enter a unique first name
    */
    @When("I enter a unique first name")
    public void i_enter_a_unique_first_name() {
        System.out.println("Test02");
    }

    /**
    * Step: Given I enter a unique last name
    */
    @And("I enter a unique last name")
    public void i_enter_a_unique_last_name() {
        System.out.println("Test03");
    }

    /**
    * Step: Given I enter a unique email address
    */
    @And("I enter a unique email address")
    public void i_enter_a_unique_email_address() {
        System.out.println("Test04");
    }

    /**
    * Step: Given I enter a unique comment
    */
    @And("I enter a unique comment")
    public void i_enter_a_unique_comment() {
        System.out.println("Test05");
    }

    /**
    * Step: Given I click on the submit button
    */
    @And("I click on the submit button")
    public void i_click_on_the_submit_button() {
       System.out.println("Test06");
    }

    /**
    * Step: Then I should be presented with a successful submission message
    */
    @Then("I should be presented with a successful submission message")
    public void i_should_be_presented_with_a_successful_submission_message() {
        System.out.println("Test07");
    }
    /**
    * Helper method to find element with wait
    */
    //private WebElement findElementWithWait(By locator) {
        //return wait.until(driver -> driver.findElement(locator));
    //}

    /**
    * Helper method to verify element is displayed
    */
    /*private boolean isElementDisplayed(By locator) {
        try {
            return driver.findElement(locator).isDisplayed();
        } catch (Exception e) {
            return false;
        }
    }*/
}
