package stepdefinitions;

import java.io.File;

import org.apache.commons.lang3.RandomStringUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.PageLoadStrategy;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.testng.Assert;

import io.cucumber.java.After;
import io.cucumber.java.Before;
import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

/**
* Cucumber Step Definitions
* Generated by Selenium-Cucumber Extension
*
* This class contains step definitions for Cucumber scenarios.
* Each method represents a step that can be used in feature files.
*/
public class StepDefinitions {

    private WebDriver driver;

    @Before
    public void setUp() {
    // Initialize WebDriver here (e.g., using WebDriverManager or manually)
    // Example: driver = new ChromeDriver();
    ChromeOptions chromeOptions = new ChromeOptions();
    chromeOptions.addArguments("--window-size=1920,1080");
    chromeOptions.addArguments("--remote-allow-origins=*");

    String os = System.getProperty("os.name").toLowerCase();

    if (os.contains("linux")) {
    chromeOptions.addArguments("--headless=new");    
    chromeOptions.addArguments("--no-sandbox");
    chromeOptions.addArguments("--disable-dev-shm-usage");
    chromeOptions.addArguments("--disable-gpu");
}
    chromeOptions.setPageLoadStrategy(PageLoadStrategy.NORMAL);
    driver = new ChromeDriver(chromeOptions);
    }

    @After
    public void tearDown() {
        // Quit WebDriver after each scenario
        driver.quit();
    }

public String generateRandomNumber(int length) {
        return RandomStringUtils.randomNumeric(length);
    }

public String generateRandomString(int length) {
        return RandomStringUtils.randomAlphabetic(length);
    }

    /**
    * Step: Given I access the WebDriver University Contact Us Page
    */
   @Given("I access the WebDriver University Contact Us Page")
    public void i_access_the_WebDriver_University_Contact_Us_Page() {
    driver.get("https://webdriveruniversity.com/Contact-Us/contactus.html");
}

    /**
    * Step: When I enter a unique first name
    */
    @When("I enter a unique first name")
    public void i_enter_a_unique_first_name() {
       driver.findElement(By.xpath("//input[@name='first_name']")).sendKeys("John" + generateRandomNumber(5));
    }

    /**
    * Step: Given I enter a unique last name
    */
    @And("I enter a unique last name")
    public void i_enter_a_unique_last_name() {
        driver.findElement(By.xpath("//input[@name='last_name']")).sendKeys("Doe" + generateRandomNumber(5));
    }

    /**
    * Step: Given I enter a unique email address
    */
    @And("I enter a unique email address")
    public void i_enter_a_unique_email_address() {
        driver.findElement(By.xpath("//input[@name='email']")).sendKeys("john.doe" + generateRandomNumber(5) + "@example.com");
    }

    /**
    * Step: Given I enter a unique comment
    */
    @And("I enter a unique comment")
    public void i_enter_a_unique_comment() {
        driver.findElement(By.xpath("//textarea[@name='message']")).sendKeys("This is a unique comment " + generateRandomString(10) +".");
    }

    @When("I enter a specific first name {word}")
    public void i_enter_a_specific_first_name_john(String firstName) 
    {
        driver.findElement(By.xpath("//input[@name='first_name']")).sendKeys(firstName);
    }
    
    @And("I enter a specific last name {word}")
    public void i_enter_a_specific_last_name_doe(String lastName) {
        driver.findElement(By.xpath("//input[@name='last_name']")).sendKeys(lastName);
    }

    @And("I enter a specific email address {word}")
    public void i_enter_a_specific_email_address(String emailAddress) {
        driver.findElement(By.xpath("//input[@name='email']")).sendKeys(emailAddress);
    }
    @And("I enter a specific comment {string}")
    public void i_enter_a_specific_comment(String string) {
    driver.findElement(By.xpath("//textarea[@name='message']")).sendKeys(string);
    }

    /**
    * Step: Given I click on the submit button
    */
    @And("I click on the submit button")
    public void i_click_on_the_submit_button() throws Exception {
        WebElement submitButton = driver.findElement(By.xpath("//input[@value='SUBMIT']"));
        TakesScreenshot ts = (TakesScreenshot) driver;
        File source = ts.getScreenshotAs(OutputType.FILE); 
        String filename = "screenshot_submit_" + System.currentTimeMillis() + ".png";
        File destination = new File("target/screenshots/" + filename); 
        org.apache.commons.io.FileUtils.copyFile(source, destination);
        submitButton.click(); 
    }

    /**
    * Step: Then I should be presented with a successful submission message
    */
    @Then("I should be presented with a successful submission message")
    public void i_should_be_presented_with_a_successful_submission_message() throws Exception {
        WebElement successMessage = driver.findElement(By.xpath("//div[@id='contact_reply']/h1"));
        Assert.assertEquals(successMessage.getText(), "Thank You for your Message!");
        TakesScreenshot ts = (TakesScreenshot) driver;
        File source = ts.getScreenshotAs(OutputType.FILE);
        String filename = "screenshot_successMessage_" + System.currentTimeMillis() + ".png";
        File destination = new File("target/screenshots/" + filename); 
        org.apache.commons.io.FileUtils.copyFile(source, destination);
    }
    
}
